export const Stretches = {
  sitting: [
    "Squat",
    "Open leg",
    "Half seated twist",
    "Toe touching (both,one leg)",
    "Kneeling (start with toe stretch)",
    "Butterfly",
    "S-sit",
    "Burma",
  ],
  standing: [
    "Ankle circles",
    "Knee circles",
    "Hip circles",
    "Breast circles",
    "Shulder circles",
    "Arm circles",
    "Elbow circles",
    "Neck circles",
    "Jaw circles",
    "Hip tilt",
    "Lateral Leg swing",
    "Medial Leg swing",
    "Breast strokes",
    "Hans behind back",
    "Wall slides",
  ],
  kneeling: ["Bird dog", "Fire hydrant", "Cat/camel", "Camel (backend)"],
} as const;
